sqlite3:
  adapter: <%= "jdbc" if defined? JRUBY_VERSION %>sqlite3
  database: awesome_nested_set.sqlite3.db
sqlite3mem:
  adapter: <%= "jdbc" if defined? JRUBY_VERSION %>sqlite3
  database: ":memory:"
postgresql:
  adapter: postgresql
  encoding: unicode
  database: awesome_nested_set_plugin_test
  pool: 5
  username: postgres
  password: postgres
  min_messages: warning
  <% if ENV['CI'] %>
  url: postgres://postgres:postgres@127.0.0.1:5432
  <% end %>
mysql:
  adapter: <%= defined?(JRUBY_VERSION) ? "jdbcmysql" : "mysql2" %>
  host: <%= ENV['CI'] ? '127.0.0.1' : 'localhost' %>
  username: root
  password:
  database: awesome_nested_set_plugin_test
  <% if ENV['CI'] %>
  port: 3306
  <% end %>
mariadb:
  adapter: <%= defined?(JRUBY_VERSION) ? "jdbcmysql" : "mysql2" %>
  host: <%= ENV['CI'] ? '127.0.0.1' : 'localhost' %>
  username: root
  password:
  database: awesome_nested_set_plugin_test
## Add DB Configuration to run Oracle tests
oracle:
  adapter: oracle_enhanced
  host: localhost
  username: awesome_nested_set_dev
  password:
  database: xe
